enum UserActions {
  SET_USER_LOADING = "SET_USER_LOADING",
  SET_USER_SUCCESS = "SET_USER_SUCCESS",
  SET_USER_FAILURE = "SET_USER_FAILURE",
}

enum PointsActions {
  ADD_POINTS_LOADING = "ADD_POINTS_LOADING",
  ADD_POINTS_SUCCESS = "ADD_POINTS_SUCCESS",
  ADD_POINTS_FAILURE = "ADD_POINTS_FAILURE",
}

export { UserActions, PointsActions };
