enum ProductsActions {
  REDEEM_PRODUCT_LOADING = "REDEEM_PRODUCT_LOADING",
  REDEEM_PRODUCT_SUCCESS = "REDEEM_PRODUCT_SUCCESS",
  REDEEM_PRODUCT_FAILURE = "REDEEM_PRODUCT_FAILURE",
}

export { ProductsActions };
